/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kykniltkmeugxfglxbvm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5a25pbHRrbWV1Z3hmZ2x4YnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NTYxODMsImV4cCI6MjA4MTUzMjE4M30.-hxqLteHzhhaxfY0ItqUFR5fs8rmaxxsGte-c0sEaT4"